### ISSUE TITLE
Error in backoffice !

### ISSUE THREAD

**Issue by vincegre** [seiyar81/prestashop-advanced-sitemap#1]
Hey,

Just updated module in my Prestashop 1.4.8.2 but I have then this error that appears on module page of my Prestashop back-office:

Strict Standards: Declaration of gadvLink::getImageLink() should be compatible with that of LinkCore::getImageLink() in /home/test-magasin/public_html/modules/prestashopadvancedsitemap/classes/gadvlink.php on line 180

Don't know if it's important error or not ??

Thanks,

Vincèn

**Comment by vincegre** [comment]
Then once module is installed in Prestashop the error disappears and everything looks to work fine !

**Comment by seiyar81** [comment]
Seems like this is related to the v1.4.8 branch of Prestashop.
Is there any product images added to your sitemap ?
I can't make any updates right now but I'll look into it as soon as I can.

**Comment by vincegre** [comment]
what do you mean by product images added to sitemap ? my products have all an image but is it your question ?
in all matters module looks to run fine once activated and setup :) so no big deal !

**Comment by seiyar81** [comment]
If you open the generated sitemap at http://yourshop/sitemap.xml, do you see any &lt;image:image&gt; in the file ?
And if you see some &lt;image:loc&gt;, are the link valid, i.e. pointing to an image.

If you can send me your sitemap, I'll look into it.

**Comment by vincegre** [comment]
My sitemap is here: http://magasin.skivr.com/sitemap.xml There are some image:image link in it that looks correct but when I click on it I get a page of my store but not a direct picture :(

**Comment by seiyar81** [comment]
Ok so there is actually a bug in the image URL generation. It's fixed in the repo, I'll tag the version later.
The products links are working fine.

Thanks for notifying me :)

**Comment by vincegre** [comment]
Thanks for so fast resolution of bug, will wait release of new package so I can update it in my store :)
